version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = false
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
enderscape = true
farmersdelight = true
somemoreblocks = true
fastpaintings = true
sawmill = true
storagedelight = true
monolib = true
snowrealmagic = true
vanillabackport = true
cobblemon = true
copperhopper = true
nether_additions = true
minecraft = true
exposure = true
