
# Not recommended, but this will allow you to use the keybinds for deleting items even if the trash slot itself is hidden.
allowDeletionWhileTrashSlotIsInvisible = false

# List of items that cannot be deleted, in comma-separated format of "modid:name".
deletionDenyList = [

    "minecraft:shulker_box",
    "minecraft:black_shulker_box",
    "minecraft:blue_shulker_box",
    "minecraft:brown_shulker_box",
    "minecraft:cyan_shulker_box",
    "minecraft:gray_shulker_box",
    "minecraft:green_shulker_box",
    "minecraft:light_blue_shulker_box",
    "minecraft:light_gray_shulker_box",
    "minecraft:lime_shulker_box",
    "minecraft:magenta_shulker_box",
    "minecraft:orange_shulker_box",
    "minecraft:pink_shulker_box",
    "minecraft:purple_shulker_box",
    "minecraft:red_shulker_box",
    "minecraft:white_shulker_box",
    "minecraft:yellow_shulker_box",
    
    "minecraft:netherite_sword",
    "minecraft:netherite_shovel",
    "minecraft:netherite_pickaxe",
    "minecraft:netherite_axe",
    "minecraft:netherite_hoe",
    "minecraft:netherite_helmet",
    "minecraft:netherite_chestplate",
    "minecraft:netherite_leggings",
    "minecraft:netherite_boots",

    "minecraft:dragon_egg",
    "minecraft:elytra",
    "minecraft:mace"
]

# Set to true if you want the delete keybindings to work in creative as well. Note: Items will be deleted permanently in creative, regardless of instantDeletion setting!
enableDeleteKeysInCreative = true

# TrashSlot will show a hint the first time the trash slot is toggled off or can be enabled on a supported screen. Set to false to disable.
enableHints = false

# This causes the deletion slot to delete items instantly, similar to Creative Mode.
instantDeletion = false

